import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "./navbar";
import { Sidebar } from "./sidebar";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="ja">
      <body className="w-screen h-screen">
        <div className="drawer lg:drawer-open">
          <input id="drawer-toggle" type="checkbox" className="drawer-toggle" />
          <div className="drawer-content flex flex-col">
            <Navbar />
            {children}
          </div>
          <div className="drawer-side shadow-md">
            <label
              htmlFor="drawer-toggle"
              aria-label="close sidebar"
              className="drawer-overlay"
            />
            <Sidebar />
          </div>
        </div>
      </body>
    </html>
  );
}
