import type { Metadata } from "next";
import "@fontsource-variable/noto-sans-jp";
import "@fontsource-variable/inconsolata";
import "./globals.css";
import { Navbar } from "./navbar";
import { Sidebar } from "./sidebar";
import { ReactNode } from "react";
import { PyodideProvider } from "./terminal/python/pyodide";
import { WandboxProvider } from "./terminal/wandbox/wandbox";
import { EmbedContextProvider } from "./terminal/embedContext";
import { AutoAnonymousLogin } from "./accountMenu";
import { DynamicMdProvider } from "./[docs_id]/dynamicMdContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="ja">
      <body className="w-screen h-screen">
        <AutoAnonymousLogin />
        <DynamicMdProvider>
          <div className="drawer lg:drawer-open">
            <input id="drawer-toggle" type="checkbox" className="drawer-toggle" />
            <div className="drawer-content flex flex-col">
              <Navbar />
              <EmbedContextProvider>
                <PyodideProvider>
                  <WandboxProvider>{children}</WandboxProvider>
                </PyodideProvider>
              </EmbedContextProvider>
            </div>
            <div className="drawer-side shadow-md z-50">
              <label
                htmlFor="drawer-toggle"
                aria-label="close sidebar"
                className="drawer-overlay"
              />
              <Sidebar />
            </div>
          </div>
        </DynamicMdProvider>
      </body>
    </html>
  );
}
