import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "./navbar";
import { Sidebar } from "./sidebar";
import { ReactNode } from "react";
import { PyodideProvider } from "./terminal/python/pyodide";
import { FileProvider } from "./terminal/file";
import { WandboxProvider } from "./terminal/wandbox/wandbox";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="ja" data-theme="light">
      <body className="w-screen h-screen">
        <div className="drawer lg:drawer-open">
          <input id="drawer-toggle" type="checkbox" className="drawer-toggle" />
          <div className="drawer-content flex flex-col">
            <Navbar />
            <FileProvider>
              <PyodideProvider>
                <WandboxProvider>{children}</WandboxProvider>
              </PyodideProvider>
            </FileProvider>
          </div>
          <div className="drawer-side shadow-md">
            <label
              htmlFor="drawer-toggle"
              aria-label="close sidebar"
              className="drawer-overlay"
            />
            <Sidebar />
          </div>
        </div>
      </body>
    </html>
  );
}
